### PR TITLE
chore: upgrade sharp to 0.31.3

### PR DESCRIPTION
**Pull request by benmccann**
- **Quick Checklist**

* [X] I have read [the contributing guidelines](../CONTRIBUTING.md)
* [ ] I have written new tests, as applicable (for bug fixes / features)
* [ ] Docs have been added / updated (for bug fixes / features)
* [X] I have added a changeset, if applicable

- **What kind of change does this PR introduce?** dependency upgrade

- **What is the new behavior (if this is a feature change)?** none

- **Does this PR introduce a breaking change?** no

- **Other information**:

### CODE REVIEW

**Comment by benmccann** [comment]
@JonasKruckenberg I'm not quite sure why this one is failing. I haven't looked at it much, but I know you've dealt with some Sharp upgrades before, so maybe you have some ideas?

**Comment by JonasKruckenberg** [comment]
will take a look 👍🏻 also what happened to dependency PRs here?

**Comment by JonasKruckenberg** [comment]
So this issue is that sharp or libvips changed the way the `quality` option for pngs works causing the produced image to be different. I would suggest we just update our test fixtures accordingly (I tried to push to your branch but I think I'm not allowed) so just run `ppm test -- -u` to update fixtures. Then you just need to update the hash in the vite test file and you're good 👍🏻

**Comment by benmccann** [comment]
Okay. I'll take a stab at updating the fixtures later

If you get to it before I do, you should be able to push to my branch

Screenshot from 2023-01-20 07-45-57

**Comment by benmccann** [comment]
Hmm. I've run that command to update the fixture. The tests still seem to be failing. I'm not sure if there's something else we need to do?

Also, the image looks much worse. I'm not sure if we're worried that the image quality has degraded or if that's just a better interpretation of the image parameter and is fine

**Comment by JonasKruckenberg** [comment]
closing in favour or #494

**Pull request closed without merging**
