### PR TITLE
fix: clone image in vite plugin to avoid dev server issue (#140)

### LINKED ISSUE #140: Generating multiple sizes only uses the last size for the entire set
Hey, another one from me ;)

I discovered a serious bug that actually completely breaks the source set generation. If you generate multiple images by chaining multiple widths together (e.g. `import srcsetAvif from '../example.jpg?w=500;700;900;1200&avif&srcset'`, as per your example), it actually only applies the last width on every image in the whole set!

To reproduce: 

1. Clone this repo and `cd` into `examples/vite-simple`
2. Edit `main.js` and add ridiculously low widths as the last params: 

```js
// ...
import srcsetAvif from '../example.jpg?w=500;700;900;1200;20&avif&srcset'
import srcsetWebp from '../example.jpg?w=500;700;900;1200;20&webp&srcset'
// ...
```
3. `yarn && yarn dev`
4. Open the page in your browser, open the devtools and reload
5. In your network tab, you'll now see the exact file that was loaded - for me it had an ID of `e78e253f7e1877238273f8472026215d31af4221` (you guessed it: it's only 20px wide 😉)
6. When inspecting srcset of the the image, however, you'll notice that the loaded ID was supposed to be 1200px wide (depending on your viewport, of couse): `/@imagetools/e78e253f7e1877238273f8472026215d31af4221 1200w,`. The one with 20px has an entirely different ID.

So, even though the 20px wide image was not selected by the browser, it still only received a 20px wide one. It looks like it's always the last argument that decides the size of all the images in the set. All of the metadata is still generated according to the parameters. Each URL is just pointing to an image the size of the last parameter.

### PR DESCRIPTION
**Pull request by jugglingcats**
- **Quick Checklist**

* [x] I have read [the contributing guidelines](../CONTRIBUTING.md)
* [ ] I have written new tests, as applicable (for bug fixes / features)
* [ ] Docs have been added / updated (for bug fixes / features)
* [x] I have added a changeset, if applicable

- **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

Fixes #140 

- **What is the new behavior (if this is a feature change)?**

None

- **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this
  PR?)

No

- **Other information**:

Am not sure if cloning an image has performance implications. Perhaps could be optimised by only cloning if there is more than one image format in the array, but didn't see worth premature optimisation.

### CODE REVIEW

**Comment by jugglingcats** [comment]
I also could not think of a way to unit test this...

**Comment by JonasKruckenberg** [comment]
Same as with #215 can you quickly rebase this against main?

**Comment by JonasKruckenberg** [comment]
Also please run `yarn changeset add` and add a `fix`bump for the vite plugin

**Review by JonasKruckenberg — APPROVED** [review]

**Comment by JonasKruckenberg** [comment]
Thanks a lot! 🙏

**Pull request merged**
