### PR TITLE
feat: add picture and source output formats

### PR DESCRIPTION
**Pull request by benmccann**
- **Quick Checklist**

* [X] I have read [the contributing guidelines](../CONTRIBUTING.md)
* [X] I have written new tests, as applicable (for bug fixes / features) - will do that tomorrow
* [X] Docs have been added / updated (for bug fixes / features)
* [X] I have added a changeset, if applicable

- **What kind of change does this PR introduce?**
Feature

- **What is the new behavior (if this is a feature change)?**
Closes https://github.com/JonasKruckenberg/imagetools/issues/260

- **Does this PR introduce a breaking change?** 
No

- **Other information**:

### CODE REVIEW

**Review by JonasKruckenberg — CHANGES_REQUESTED** [review]
Okay just a couple of small things:

1. add a test case for the formats here https://github.com/JonasKruckenberg/imagetools/blob/main/packages/core/src/__tests__/output-formats.test.ts
2. add docs to this file https://github.com/JonasKruckenberg/imagetools/blob/main/docs/directives.md

But I actually have one bigger question: What benefit does the `source` output format has over using `metadata=src;width`? I'm not against it, just wondering. The fact that the `metadata`  format accepts a whitelist is a little advertised feature too.

**Comment by benmccann** [comment]
I've added docs and tests now

>What benefit does the source output format has over using metadata=src;width?

I added some docs to the type explaining: https://github.com/JonasKruckenberg/imagetools/pull/369/files#diff-4c2458380e50c967c70d7afe819dc7412180f9f817043f27441de3498e4d0479R31

**Comment by zerodevx** [comment]
Hi all, since we're on the topic of `outputFormats`, I was wondering if we can `async` this too:

https://github.com/JonasKruckenberg/imagetools/blob/b84387434d60e7ea53c6fb806134e8f1d24e6243/packages/vite/src/index.ts#L109-L113

Like so:

```js
return dataToEsm(await outputFormat(outputMetadatas), { ... }
```

It's possible that an `outputFormat` is an `async` op, for eg. generating the `base64` of a low-quality image placeholder. This enables a consumer to extend in `vite.config.js`:

```js
const config = {
  plugins: [sveltekit(), imagetools({
    extendOutputFormats: (defaults) => ({
      ...defaults,
      inline: () => async (metas) => {
        const out = []
        for (const { image, format } of metas) {
          const buffer = await image.toBuffer()
          out.push(`data:image/${format};base64,${buffer.toString('base64')}`)
        }
        return out.length === 1 ? out[0] : out
      }
    })
  )]
}
```

Does this make sense?? 🤔

**Comment by benmccann** [comment]
@zerodevx it sounds like a good idea, but I'd rather do it separately than expand the scope of this PR. can you file a new issue for it?

**Review by JonasKruckenberg — APPROVED** [review]

**Comment by s3812497** [comment]
Hi @benmccann . Is there a way for the `picture` directive to output the height as well?

I'm trying to migrate to this from the [old solution provided here](https://github.com/JonasKruckenberg/imagetools/issues/260#:~:text=commented-,on%20Jan%2011,-i%20did%20something).

Currently, when using `picture`, it's difficult to set the height to calculate the aspect ratio of the image. It also overrides the `metadata` directive, so it can't be mixed.

I've been using this setup with SvelteKit and it's almost perfect:
```js
// vite.config.js
const config = {
	plugins: [
		sveltekit(),
		imagetools({
			defaultDirectives: (id) => {
				if (id.searchParams.has('optimize')) {
					return new URLSearchParams(
						'w=1920;1366;780;414&format=avif;webp;jpg&meta=width;height;src;format'
					);
				}
				if (id.searchParams.has('placeholder')) {
					return new URLSearchParams('w=54&blur=2&jpg');
				}
				return new URLSearchParams();
			},
		})
	]
};

// +page.svelte
import Image1 from '$images/dog.jpg?optimize';
```
with an `Image.svelte` component[ adapted from this example.](https://github.com/JonasKruckenberg/imagetools/issues/260#:~:text=commented-,on%20Jan%2011,-i%20did%20something)

**Comment by benmccann** [comment]
@s3812497 can you share the `Image` component you're using to show how you are using the `height`? It's probably best to file the request as a new issue so that it doesn't get lost in a closed PR

**Pull request merged**
