### PR TITLE
feat: Add ability to override resolveConfigs in vite plugin

### PR DESCRIPTION
**Pull request by jugglingcats**
- **Quick Checklist**

* [X] I have read [the contributing guidelines](../CONTRIBUTING.md)
* [x] I have written new tests, as applicable (for bug fixes / features)
* [x] Docs have been added / updated (for bug fixes / features)
* [x] I have added a changeset, if applicable

- **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

This pull request relates to #139. It adds ability to supply a custom `resolveConfigs`.

- **What is the new behavior (if this is a feature change)?**

If you don't set property in config everything works the same as before. You can supply a function that will be called in place of the default `resolveConfigs`. If this function doesn't return a value, the existing `resolveConfigs` is called, otherwise the result of the custom `resolveConfigs` is used.

Below is an example of a custom implementation. If you add `?glowsite=<preset>` to an image import it will generate images with preset widths in webp format.

```
const defaultPresets = {
    default: {widths: [300, 800, 1200]}
}

export function glowsiteImageToolsPresets(pluginConfig) {
    const presets = pluginConfig?.presets || defaultPresets

    return function (config) {
        const glowsite_config = config.find(([key]) => key === "glowsite")
        if (glowsite_config) {
            const [, [value]] = glowsite_config
            const preset_name = value.trim().length ? value.trim() : "default"
            const preset = presets[preset_name] || defaultPresets.default
            const widths = preset.widths

            return widths.map(width => ({
                width,
                webp: ""
            }))
        }
    }
}
```

```
// vite.config.js
...
export default {
    plugins: [
        react(),
        imagetools({
            resolveConfigs: glowsiteImageToolsPresets({default: {widths: [100,200,300]}})
        }),
...
```

- **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this
  PR?)

No (intentional) breaking changes.

- **Other information**:

If you think this PR might be accepted I can add tests, docs, changeset, etc.

I had trouble running the tests on Windows (and on Ubuntu actually) after clean checkout of your repo, so might need some help resolving that before I can add tests.

^--- issue on Ubuntu is probably git-lfs issue (similar to #210) in which case I can workaround Windows issue

### CODE REVIEW

**Comment by JonasKruckenberg** [comment]
Looks good to me! This is in many regards better than all the solutions I have thought of, since it actually works 😄.
I'd propose changing it to a function that receives the configs array and must return a config array 🤔 so a preset could also modify and not replace the configs.
But besides that I'll be happy to include this! Please make sure to add tests and all that 👍🏻 
Thanks for your patience

**Comment by JonasKruckenberg** [comment]
Actually, I just realized that this might be a bit redundant if my proposal in #139 gets merged. Or is there something I am missing?

**Comment by jugglingcats** [comment]
Hi @JonasKruckenberg, have ported to rollup plugin, added a test in both and added a section to the guide.

I made a comment in #139 which I hope explains why this option provides more flexibility over the `defaultConfigs` route.

I did not implement your request to accept and return a config array. Might just be me being lazy but I feel if you are overriding `resolveConfigs` you probably want complete control and don't care what the default resolution would be. And if you really need it you can call the core `resolveConfigs` easily enough. If you feel strongly I can look at it again!

**Comment by JonasKruckenberg** [comment]
Good point, the core `resolveConfigs` function is part of the public API. Could you just add a short sentence in the docs to mention this?
And the changeset it just a markdown file in the `.changeset` folder, but you can also run `yarn changeset add` in the project directory and the cli will guide you through the process. Make to sure to include minor bumps for the vite and rollup plugin though!

**Comment by JonasKruckenberg** [comment]
Sorry, forgot to update the PR check workflow to use node 16.x instead 15.x. Can you quickly rebase against main again so we can run the checks? Thanks!

**Comment by JonasKruckenberg** [comment]
Awesome work! Sorry for adding this so late in the process, but what do you think of renaming it to `overrideConfigs`? I guess that'd make it clearer what that hook is useful for 🤔

**Comment by jugglingcats** [comment]
Hi I think that might be confusing for a couple of reasons, a) people looking at the code wouldn't immediately make a link between `overrideConfigs` and `resolveConfigs`, b) `overrideConfigs` doesn't immediately shout function to me, I would expect it to be an override value.

I would vote for leaving as it is, or consider changing to `overrideResolveConfigs`...! Happy to make that change if you agree.

**Comment by JonasKruckenberg** [comment]
yeah, that makes sense to me!

**Review by JonasKruckenberg — APPROVED** [review]

**Pull request merged**
